version: '3.8'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynet
  db:
    build: ./db
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
